a =input('Input your first number:  ')
b =input('Input your second number: ')
c =input('Input your third number:  ')
d =input('Input your fourth number: ')
e =input('Input your fifth number:  ')
print("Float of "+a+"Equal",float(a))
print("Complex of "+a+"Eqial",complex(a))
print("Float of "+b+"Equal",float(b))
print("Complex of "+b+"Eqial",complex(b))
print("Float of "+c+"Equal",float(c))
print("Complex of "+c+"Eqial",complex(c))
print("Float of "+d+"Equal",float(d))
print("Complex of "+d+"Eqial",complex(d))
print("Float of "+e+"Equal",float(e))
print("Complex of "+e+"Eqial",complex(e))